FROM ubuntu:14.04
MAINTAINER Klaus Ma <klaus1982.cn@gmail.com>

RUN apt-get update && apt-get install -y openjdk-7-jdk

RUN apt-get install -y curl

ENV JAVA_HOME /usr

WORKDIR /usr/local

RUN curl -L http://mirrors.sonic.net/apache/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz | tar xz

WORKDIR /usr/local/hadoop-2.7.2

