FROM ubuntu:14.04
MAINTAINER Klaus Ma <klaus1982.cn@gmail.com>

RUN apt-get update && apt-get install -y openjdk-7-jdk

ENV JAVA_HOME /usr

COPY zookeeper-3.4.9 /usr/local/zookeeper-3.4.9

WORKDIR /usr/local/zookeeper-3.4.9

CMD ["./start_zk.sh"]
