FROM ubuntu:16.04
MAINTAINER Klaus Ma <klaus1982.cn@gmail.com>

RUN apt-get update && apt-get install -y openjdk-8-jdk libapr1-dev libsvn-dev libcurl4-nss-dev libsasl2-dev libsasl2-modules

ENV JAVA_HOME=/usr

COPY hadoop-2.7.2 /usr/loca/hadoop-2.7.2

WORKDIR /usr/loca/hadoop-2.7.2

ENV USER root

CMD ["./start_myriad.sh"]

