version: '2'
services:
  mesosslave:
    image: k82cn/mesos-slave:0.28.2-2.0.27.ubuntu1404.jdk7
    depends_on:
    - mesosmaster
    environment:
      - MESOS_MASTER=mesosmaster:5050
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - ${PWD}/log/mesos:/var/log/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
    links:
      - mesosmaster
  mesosmaster:
    image: mesosphere/mesos-master:0.28.2-2.0.27.ubuntu1404
    ports:
      - "5050:5050"
    environment:
      - MESOS_PORT=5050
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
    volumes:
      - ${PWD}/log/mesos:/var/log/mesos
      - ${PWD}/tmp/mesos:/var/tmp/mesos
  httpserver:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ${PWD}:/usr/share/nginx/html:ro
  zk:
    image: k82cn/zk:3.4.9
    ports:
      - "2181:2181"
